name: Build and Deploy Blazor WASM App to Github Pages

on: 
  workflow_dispatch:
  push:
    branches: main

permissions: 
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PersonalWebsite.sln

      - name: Publish .NET project
        run: dotnet publish -c Release -o release

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: release/wwwroot
