name: (v2) Build and Deploy .NET to GitHub Pages

on: 
  workflow_dispatch:
  push:
    branches: main

permissions: 
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET WASM Tools
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore PersonalWebsite.sln

      - name: Publish .NET project
        run: dotnet publish PersonalWebsite.sln -c:Release -o:release -p:GHPages=true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true
